### ISSUE TITLE
Has Google just made getting credentials.json more tedious?

### ISSUE THREAD

**Issue by Clement-Lelievre** [asweigart/ezgmail#33]
A few months back, I implemented the procedure described in the README and it worked perfectly, in particular as regards the way to obtain _credentials.json_ and _token.json_.
Now coming back to it and going through the whole thing again, I visited [https://developers.google.com/gmail/api/quickstart/python](https://developers.google.com/gmail/api/quickstart/python) as per the README but the **'Enable the Gmail API'** button was, this time, nowhere to be found.
After some research, I still managed to get a proper account and to finally send email with Python, but only through non trivial trials in the **Google Cloud Console**, setting up a project, then Oauth etc.

So, unless I missed a simpler way to proceed, which is possible, is it time to update the README in order to adjust to this fresh, harder Google account setup?

**Comment by elliotkantor** [comment]
Yeah, Google definitely changed this since reading Automate the Boring Stuff. I made these changes to the readme in PR #34

**Comment by micjgam** [comment]
So... I just went through this rigamarole as well with GCP.  In the end, I was able to generate the credentials.json file and the subsequent token.json.

However, now I am getting a KeyModule error when calling ezgmail.init().  I have the prerequisite modules and files already.  All solutions say to delete the token.json file and rerun the authorization process, but this does not work.

Any other solutions out there?

**Comment by chernoar** [comment]
I find myself having to reauthenticate once every week or so (GMail opens the browser, asks for permissions and then generates a verification code to paste in the console). 

I'm reading things about refresh tokens which can be obtained.
Did anyone figure out a more permanent solution compatible with EZGmail?

**Comment by asweigart** [comment]
Yes, the process is much more tedious now, but I've written out all the steps in the README. I'm looking into how to make this easier to do in the future.
