### ISSUE TITLE
No "Enable the Gmail API" button anymore. How to download credential.json

### ISSUE THREAD

**Issue by bileeve** [asweigart/ezgmail#40]
There's no "Enable the Gmail API" button at [Python QuickStart](https://developers.google.com/gmail/api/quickstart/python ) anymore. How to download credentials.json?

**Comment by awebmekhilef** [comment]
Google now requires you to create a Google Cloud project to access their APIs. 

See [Create a Google Cloud project](https://developers.google.com/workspace/guides/create-project) and [Enable Google Workspace APIs](https://developers.google.com/workspace/guides/enable-apis).

**Comment by asweigart** [comment]
I've updated the readme with instructions about how to go to the Google Cloud Console, create a new project, enable the Google Sheets and Google Drive APIs, create a new OAuth client credential and test user, download the credentials json file, then sign in with your Google account to create the token json file. Oooof. The individual steps are easy, but there's quite a few of them. I'm looking into how to make this process easier.
